language: generic # don't install any environment

sudo: required
dist: trusty

install:
- pip install "notebook==4.1" requests jupyter_cms jupyter_dashboards

addons:
  apt_packages:
    - pandoc

script: bash tools/travis-deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: d7e0dc08b1d8
  - COMMIT_AUTHOR_EMAIL: "dds@aueb.gr"
